Develop
fadeevdmy3751/LizaAlert-project pull request #1
Opened 2022-04-28 13:26 UTC by fadeevdmy3751

We are ready!

2022-04-29 11:12 UTC, vgschevchenko requested changes
Отличная работа, но остались некоторые моменты к исправлению.
Вы все молодцы, отлично постарались.
Работа оставила приятное впечатление. 
Исправьте все ошибки и работа будет принята. 
Вы справитесь, желаю вам успехов. 

Остались некоторые моменты, которые лучше всего исправить, чтобы можно было спокойно добавить работу в портфолио. 

1. Соответствие макету
    - [x] <!--12.0--> 1.1 Все элементы из макета сверстаны
    **Комментарий: отсутвует блок "название блока" [скриношт или ссылка на скриншот]**
    - [ ] <!--5.0--> 1.2 шрифты, размер, цвет и начертания текста соответствуют макету
    **Комментарий: шрифт ссылок в футере не соответвует макету [скриношт или ссылка на скриншот]**
	
## Критерии

1. Соответствие макету:
    - [x] <!--12.0--> 1.1 Все элементы из макета сверстаны
    - [x] <!--5.0--> 1.2 Шрифты, размер, цвет и начертания текста соответствуют макету
    - [x] <!--5.0--> 1.3 Ширина элементов и отступы отличаются от макета не более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета
    - [x] <!--3.0--> 1.4 Все блоки соответствуют макету в последних версиях Firefox, Google Chrome или Yandex Browser
2. Адаптив:
    - [x] <!--4.0--> 2.1 На всех размерах экрана 320px и более отсутствует горизонтальный скролл
    - [x] <!--1.0--> 2.2 Установленная максимальная ширина контента соответствует макету
    - [x] <!--4.0--> 2.3 Вёрстка не ломается между брейкпоинтами
    - [x] <!--1.0--> 2.4 Брейкпоинты сгруппированы. Если два брейкпоинта имеют небольшую пиксельную разницу в медиа-правиле, они объединены в один
    - [x] <!--4.0--> 2.5 Текст не выпадает из блоков на всех размерах экрана 320px и более 
    - [x] <!--3.0--> 2.6 Изображения не искажаются и выглядят как в макете на всех размерах экрана
    - [x] <!--1.0--> 2.7 Одинаковые свойства в разных медиа-правилах не дублируются
3. Верстка:
    - [x] <!--4.0--> 3.1 Нет ошибок валидации [https://validator.w3.org/nu/](https://validator.w3.org/nu/) (Erorrs)
    - [x] <!--3.0--> 3.2 Используются `<main>`, `<section>`, `<header>`, `<footer>`, `<ul>`, `<nav>`, `<h1-h6>` и `<p>` там, где это необходимо
    - [x] <!--2.0--> 3.3 Не используются элементы `<b>`, `<br>`, `<i>`
    - [ ] <!--1.0--> 3.4 Отсутствуют лишние `div` обёртки 
    - [x] <!--3.0--> 3.5 Контентные картинки вставлены через `<img>` и в них присутствует `alt` с описанием, соответствующим языку страницы
    - [x] <!--2.0--> 3.6 На странице есть заголовок первого уровня
    - [x] <!--2.0--> 3.7 Заголовки соответствуют иерархии страницы
    - [x] <!--1.0--> 3.8 Корректно задан `viewport`, прописаны `title` и `lang`.
4.  CSS:
    - [x] <!--2.0--> 4.1 Не используется `!important`
    - [x] <!--2.0--> 4.2 Абсолютное позиционирование не используется без непосредственной необходимости
    - [x] <!--4.0--> 4.3 Использование `height` и `max-height` не приводит к выпадению текста или блоков при переполнении
    - [ ] <!--2.0--> 4.4 Любой интерактивный элемент имеет состояние наведения, состояние наведения берется из макета или используется прозрачность
    - [x] <!--1.0--> 4.5 Для каждого шрифта указаны альтернативные варианты из системных шрифтов и тип шрифта
5. Применение БЭМ:
    - [x] <!--4.0--> 5.1 Нет нарушения методологии БЭМ: нет элементов без родительского блока, нет элементов элементов, модификаторы не используются без указания того, что они модифицируют
    - [x] <!--2.0--> 5.2 Не используются селекторы по тегу
    - [ ] <!--3.0--> 5.3 Для одинаковых блоков в макете переиспользуется стили одного БЭМ-блока
	**Комментарий: Эти два элемента имеют похожие стили. Им можно сделать общий класс или использовать `tag` внутри `card`, а уникальные стили переопределить через модификатор. 
https://skr.sh/sDhckO8VLIa**
    - [x] <!--1.0--> 5.4 Числа в названиях классов не используются, за исключением классов для элементов, указанных в руководстве по стилю (Style Guide)
    - [x] <!--1.0--> 5.5 Модификатор не отражает позицию элемента в разметке (`paragraph_first`)
    - [ ] <!--1.0--> 5.6 Модификаторы не содержат дубли стилей модифицируемого элемента или блока, только изменяющиеся свойства
    - [x] <!--2.0--> 5.7 Файловая структура построена по БЭМ nested
- [x] <!--10.0--> 6. Функциональность на JS работает корректно (слайдеры, бургерное меню или другие требования согласно заданию на проект)
7. Структура проекта и оформление кода
    - [x] <!--2.0--> 7.1 Соблюдена единообразная файловая структура проекта, например, изображения в папке `images`, шрифты в папке `fonts`, стили в папке `blocks`, скрипты в папке `scripts`, а не разбросаны в разных папках и не хранятся в корне проекта
    - [x] <!--1.0--> 7.2 Код в проекте отформатирован единообразно
    - [x] <!--1.0--> 7.3 Нет нарушений иерархии отступов в разметке, стилях и файлах скриптов

## Доп. комментарии:

## Количество баллов: 93

##

2022-04-29 11:12 UTC, vgschevchenko commented on profile.html
> +<!DOCTYPE html>
Отлично: 	* Валидатор `html` не ругается на ошибки.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +<!DOCTYPE html>
Отлично: 	* Валидатор `html` не ругается на ошибки.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +<head>
• Отлично дополнили `head`, указав соответствующие `meta` теги.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +        <button class="filters__category">Категория</button>
Необходимо указать тип для ВСЕХ КНОПОК в коде. 
Если это обычная кнопка, то тогда тип `button`. 
Это полезно для доступности в будущем при разработки, а также и для сео. 
По внешнему виду кнопки разного типа никак не различаются, но у каждой такой кнопки свои функции. https://webref.ru/html/button/type

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +        <div class="filters__panel">
Это лишняя `div` обёртка.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +      <div class="tags">
Можно лучше:
Для улучшения семантики перечисляемые блоки можно выделить в список `ul`. 
Обратите внимание, что у списков следует убрать стандартные стили: `margin`, `padding`, `list-style-type`

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +      <div class="card__options">
Можно лучше:
Для улучшения семантики перечисляемые блоки можно выделить в список `ul`. 
Обратите внимание, что у списков следует убрать стандартные стили: `margin`, `padding`, `list-style-type`

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +        <div class="tag tag-novice">
Эти два элемента имеют похожие стили. 
Им можно сделать общий класс или использовать `tag` внутри `card`, а уникальные стили переопределить через модификатор. 
https://skr.sh/sDhckO8VLIa

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +        <span class="card__level"></span>
Эти два элемента имеют похожие стили. 
Им можно сделать общий класс или использовать `tag` внутри `card`, а уникальные стили переопределить через модификатор. 
https://skr.sh/sDhckO8VLIa

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +          <button aria-label="Удалить" class="tag__delete" type="button"></button>
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице. 

https://skr.sh/sDhClAY3E2d

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +      <button class="header__button-courses header__button-courses_active" type="button"></button>
Это не кнопки, а ссылки `a`.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +      <button class="header__button-profile" type="button"></button>
Это не кнопки, а ссылки `a`.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +      <button class="header__button-courses header__button-courses_active" type="button"></button>
Можно лучше:
Для улучшения семантики перечисляемые блоки можно выделить в список `ul`. 
Обратите внимание, что у списков следует убрать стандартные стили: `margin`, `padding`, `list-style-type`

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +          <ul class="filters__list">
• Отличное решение воспользоваться списком для перечисляемых элементов.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +        <button class="card__button"></button>
Необходимо указать тип для ВСЕХ КНОПОК в коде. 
Если это обычная кнопка, то тогда тип `button`. 
Это полезно для доступности в будущем при разработки, а также и для сео. 
По внешнему виду кнопки разного типа никак не различаются, но у каждой такой кнопки свои функции. https://webref.ru/html/button/type

2022-04-29 11:12 UTC, vgschevchenko commented on profile.html
> +      <ul class="profile-account__status">
• Отличное решение воспользоваться списком для перечисляемых элементов.

2022-04-29 11:12 UTC, vgschevchenko commented on profile.html
> +    <div class="form-container form-container_place_profile-data">
Это лишняя `div` обёртка.

2022-04-29 11:12 UTC, vgschevchenko commented on profile.html
> +      <form class="form form_type_personal-data" method="post">
Для формы необходимо указать уникальное имя(атрибут) `name`.
Данный атрибут задает форме уникальность для ее поиска в dom дереве и  для последующей работы с введенными в нее данными и манипуляциями при помощи javaScript и т.д
https://webref.ru/html/form/name

2022-04-29 11:12 UTC, vgschevchenko commented on profile.html
> +    <div class="form-container form-container_place_account-data">
Это лишняя `div` обёртка.

2022-04-29 11:12 UTC, vgschevchenko commented on profile.html
> +      <form class="form form_type_account" method="post">
Для формы необходимо указать уникальное имя(атрибут) `name`.
Данный атрибут задает форме уникальность для ее поиска в dom дереве и  для последующей работы с введенными в нее данными и манипуляциями при помощи javaScript и т.д
https://webref.ru/html/form/name

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +      <button class="header__button-courses header__button-courses_active" type="button"></button>
У все ссылок в навигации должен быть общий класс, а модификатора добавляется активной.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-courses/header__button-courses.css
> +.header__button-courses {
Используются разные классы для элементов навигации. 
У них должен быть один общий класс и модификатор, которые добавляется активному элементу.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-courses/header__button-courses.css
> +}
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-profile/header__button-profile.css
> +}
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/profile-account/__button-exit/profile-account__button-exit.css
> +}
Можно лучше:
Для плавных переходов на интерактивных элементах, можно использовать свойство `transition`.
Обычно такие вещи радуют глаз и делают взаимодействие приятным. 
Обратите внимание ниже в примере, где и как применяются данное свойство.
https://webref.ru/css/transition

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/__submit-btn/form__submit-btn.css
> +}
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице. 

https://skr.sh/sDhqDaSC8Te

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__button/_style/card__button_style_inProgress.css
> +}
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице. 

https://skr.sh/sDhf6O4jYyt

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__button/_style/card__button_style_available.css
> +}
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице. 

https://skr.sh/sDh9yhBWBWA

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/filters/__label/filters__label.css
> +}
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице. 

https://skr.sh/sDhBtsmmI43

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/filters/__panel/filters__panel.css
> +  transition: max-height 0.3s linear;
Отлично: плавное развертывание списка.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/filters/__category/filters__category.css
> +}
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице. 

https://skr.sh/sDhIZRD5C3v

2022-04-29 11:12 UTC, vgschevchenko commented on README.md
> +
Можно лучше:

* Добавить  ссылку на gh-pages.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__button/card__button.css
> +  height: 48px;
Можно лучше:

Данному элементу можно не ограничивать жестко высоту. Если вдруг контента(текста) станет больше, чтобы элемент имел возможность расшириться, а иначе верстка сломается.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__clock/card__clock.css
> +.card__clock {
Эти элементы имеют общие стили, но классы у них разные и получается дублирование кода. 
Меняется только иконка. 
https://skr.sh/sDhC1fCWzJn

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__lessons/card__lessons.css
> +.card__lessons {
Эти элементы имеют общие стили, но классы у них разные и получается дублирование кода. 
Меняется только иконка. 
https://skr.sh/sDhC1fCWzJn

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__book-img/card__book-img.css
> +.card__book-img {
Эти элементы имеют общие стили, но классы у них разные и получается дублирование кода. 
Меняется только иконка. 
https://skr.sh/sDhJyAW1fCh

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__clock-img/card__clock-img.css
> +.card__clock-img {
Эти элементы имеют общие стили, но классы у них разные и получается дублирование кода. 
Меняется только иконка. 
https://skr.sh/sDhJyAW1fCh

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__description/card__description.css
> +.card__description {
Эти элементы имеют общие стили, но классы у них разные и получается дублирование кода. 
https://skr.sh/sDhpeCSM6Gl

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__subtitle/card__subtitle.css
> +.card__subtitle {
Не нашел применение данного элемента, если он лишний, то его нужно удалить.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__subtitle/card__subtitle.css
> +  height: 72px;
Мы не указываем текстовым элементам фиксированную высоту.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/__texts/card__texts.css
> +  height: 240px;
Мы не указываем текстовым элементам фиксированную высоту.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/card/card.css
> +  height: 240px;
Мы не указываем текстовым элементам фиксированную высоту.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/__input/form__input.css
> +.form__input::placeholder {
У псевдоклассов присутствуют общие стили. 
Было бы отлично их не дублировать, а объединить.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/__input/form__input.css
> +.form__input::-webkit-input-placeholder {
У псевдоклассов присутствуют общие стили. 
Было бы отлично их не дублировать, а объединить.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/__input/form__input.css
> +.form__input::-moz-placeholder {
У псевдоклассов присутствуют общие стили. 
Было бы отлично их не дублировать, а объединить.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/__input/form__input.css
> +.form__input::-ms-input-placeholder {
У псевдоклассов присутствуют общие стили. 
Было бы отлично их не дублировать, а объединить.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/__input/_type/form__input_type_attach.css
> +.form__input_type_attach {
Считается хорошей практикой не дублировать стили в модификатор, которые уже содержаться у элемента или блока. 
Все общие свойства хранят в классе элемента или блока. 
В модификаторе указывают лишь новые или изменяемые стили.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/__input/_type/form__input_type_edit.css
> +.form__input_type_edit {
Считается хорошей практикой не дублировать стили в модификатор, которые уже содержаться у элемента или блока. 
Все общие свойства хранят в классе элемента или блока. 
В модификаторе указывают лишь новые или изменяемые стили.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/form/form.css
> +.form {
Директория с пустыми модификаторами. 

Пустые селекторы, медиазапросы, а также их файлы  или директории - лучше не оставлять.
Это хорошая привычка и признак внимательности к своей работе.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-courses/_active/header__button-courses_active.css
> +  background-image: url(../../../../images/button-courses_active.svg);
Стилизовать нужно текст, который предложен в макете, а не заменять его изображением.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-courses/_active/header__button-courses_active.css
> +
Внутри модификатора должны остаться только стили изменяющие его, когда элемент активен. 

Считается хорошей практикой не дублировать стили в модификатор, которые уже содержаться у элемента или блока. 
Все общие свойства хранят в классе элемента или блока. 
В модификаторе указывают лишь новые или изменяемые стили.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-courses/header__button-courses.css
> +  background-image: url(../../../images/button-courses.svg);
Стилизовать нужно текст, который предложен в макете, а не заменять его изображением.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-profile/_active/header__button-profile_active.css
> +  background-image: url(../../../../images/button-profile_active.svg);
Стилизовать нужно текст, который предложен в макете, а не заменять его изображением.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-profile/header__button-profile.css
> +  background-image: url(../../../images/button-profile.svg);
Стилизовать нужно текст, который предложен в макете, а не заменять его изображением.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/header/__button-profile/_active/header__button-profile_active.css
> +}
Внутри модификатора должны остаться только стили изменяющие его, когда элемент активен.

Считается хорошей практикой не дублировать стили в модификатор, которые уже содержаться у элемента или блока. Все общие свойства хранят в классе элемента или блока. В модификаторе указывают лишь новые или изменяемые стили.

2022-04-29 11:12 UTC, vgschevchenko commented on index.html
> +  <main class="index-content">
Для `main` созданны разные классы. Это не очень хороший подход. 
Нужно создать общий класс, а уникальные стили для каждой страницы задать через модификатор, тем самым избавляясь от дубликатов.

2022-04-29 11:12 UTC, vgschevchenko commented on profile.html
> +  <main class="profile-content">
Для `main` созданны разные классы. Это не очень хороший подход. 
Нужно создать общий класс, а уникальные стили для каждой страницы задать через модификатор, тем самым избавляясь от дубликатов.

2022-04-29 11:12 UTC, vgschevchenko commented on blocks/text-tips/text-tips.css
> +}
Элемент text-tips__list-item.css пустой. 

Пустые селекторы, медиазапросы, а также их файлы  или директории - лучше не оставлять.
Это хорошая привычка и признак внимательности к своей работе.

2022-04-30 11:46 UTC, RuslanAf commented on blocks/form/__submit-btn/form__submit-btn.css
> +}
Hover добавлен

2022-04-30 11:48 UTC, RuslanAf commented on blocks/text-tips/text-tips.css
> +}
Элемент text-tips__list-item.css удален

2022-04-30 11:51 UTC, RuslanAf commented on profile.html
> +      <form class="form form_type_personal-data" method="post">
Добавлено name="personal-data-form"

2022-04-30 11:52 UTC, RuslanAf commented on profile.html
> +      <form class="form form_type_account" method="post">
Добавлено name="account-form"

2022-04-30 11:57 UTC, RuslanAf commented on blocks/form/__input/_type/form__input_type_attach.css
> +.form__input_type_attach {
Убран дублированный код.

2022-04-30 11:57 UTC, RuslanAf commented on blocks/form/__input/_type/form__input_type_edit.css
> +.form__input_type_edit {
Убран дублированный код.

2022-05-04 08:33 UTC, fadeevdmy3751 commented on index.html
> +        <div class="filters__panel">
Убрал div.filters__panel, css перекинул в ul.filters__list, подправив margin в filters__item

2022-05-04 11:08 UTC, fadeevdmy3751 commented on blocks/card/__lessons/card__lessons.css
> +.card__lessons {
У card__clock и card__lessons разные margin, а это единственное их свойство.

2022-05-04 11:08 UTC, fadeevdmy3751 commented on blocks/card/__clock/card__clock.css
> +.card__clock {
У card__clock и card__lessons разные margin, а это единственное их свойство.

2022-05-05 10:08 UTC, closed without merging